### PR TITLE
Update template-registry.ts

### PR DESCRIPTION
**Pull request by RobbieTheWagner**
Thanks for this addon! I think we should update the interface name to be `Registry` so this will work and merge together with the others.

### CODE REVIEW

**Comment by ijlee2** [comment]
Hi, @RobbieTheWagner. Thanks for your feedback.

I didn't quite understand what you might have meant by "this will work and merge together with the others." Can you clarify what you had in mind, as to how the consuming project would consume the interface?

From what I've observed, the naming convention that many addons follow is `<MyAddon>Registry`. But the name that the addon uses doesn't matter, as long as it uses a default export to export the interface. Even with a named export, the consuming project can always rename the addon's interface to avoid name collisions.

In case you might have missed [the sample code for setup](https://github.com/ijlee2/ember-container-query/tree/5.0.12?tab=readme-ov-file#installation):

```ts
/* types/index.d.ts (the code below can be written in some other file) */

import '@glint/environment-ember-loose';

import type EmberContainerQueryRegistry from 'ember-container-query/template-registry';

declare module '@glint/environment-ember-loose/registry' {
  export default interface Registry extends EmberContainerQueryRegistry, /* other addon registries */ {
    // local entries
  }
}
```

**Comment by RobbieTheWagner** [comment]
Hi @ijlee2 this addon is the only one where the types did not work when importing and extending the template registry interface. This led me to look deeper and I noticed the other addons we are using call the interface `Registry`. This led me to believe that since this addon is the only one that does not, perhaps the naming is the issue. TS will auto merge interfaces for you, so if we name them all `Registry` I think we benefit from that merging, but I could be wrong.

**Comment by ijlee2** [comment]
> where the types did not work

Can you be more specific (e.g. Glint didn't work) and provide the error message that you saw?

At the moment, I don't think the interface name could be the reason. But maybe how your project configures TypeScript (e.g. in `tsconfig.json`)?

To my basic understanding, importing a type can be assumed to work like importing a value in JavaScript, i.e. we can use default/named imports and rename things to avoid a name collision. If you can provide a minimum reproduction, that'll help us narrow possible suspects.

**Comment by RobbieTheWagner** [comment]
> > where the types did not work
> 
> Can you be more specific (e.g. Glint didn't work) and provide the error message that you saw?
> 
> At the moment, I don't think the interface name could be the reason. But maybe how your project configures TypeScript (e.g. in `tsconfig.json`)?
> 
> To my basic understanding, importing a type can be assumed to work like importing a value in JavaScript, i.e. we can use default/named imports and rename things to avoid a name collision. If you can provide a minimum reproduction, that'll help us narrow possible suspects.

@ijlee2 I do not know the specifics, but since all other addons use `Registry` and all of them work for us, you might want to consider making this change. Types were not found for this addon and glint blew up. I did import them and use them to extend, but it didn't work.

**Comment by ijlee2** [comment]
Last week, I reached out to @RobbieTheWagner on Discord to see if I could pair on debugging. Robbie explained, he went with removing `ember-container-query` as the project's dependency.

For now, I'll close the pull request as a won't fix. I'll keep an eye out on how Glint will be changed in the near future.

**Comment by RobbieTheWagner** [comment]
> Last week, I reached out to @RobbieTheWagner on Discord to see if I could pair on debugging. Robbie explained, he went with removing `ember-container-query` as the project's dependency.
> 
> 
> 
> For now, I'll close the pull request as a won't fix. I'll keep an eye out on how Glint will be changed in the near future.
> 
> 

- [ ] I'm still not sure why you wouldn't want to make this change. I understand you think it is not necessary, but it would be in line with the way all the other addons are doing it and it _could_ help people. Not sure there is any downside to renaming.

**Comment by RobbieTheWagner** [comment]
> For now, partly because a rewrite of Glint is in progress, I want to follow Glint's documentations, which show prefixing `Registry` with the addon's name on the addon's side, and using `extends` to compose template registries on the consumer's side.
> 
> * Addon: https://typed-ember.gitbook.io/glint/environments/ember/authoring-addons#publishing-addons-with-glint-types
> * Consumer: https://typed-ember.gitbook.io/glint/environments/ember/using-addons#using-glint-enabled-addons
> 
> Maybe I'm still misunderstanding how your project is set up, as I didn't get to see code. What I understood was, by naming every template registry to be `Registry`, the consumer doesn't need to extend the registries, because TypeScript knows to combine them automatically. Is this right?

@ijlee2 I am honestly quite tired of debating a simple name change. I am importing all the registries and extending, as you and every other addon suggest. Everyone elses' addons, like literally every one of them, uses `Registry` and all of them work seamlessly, but yours does not. I do not know why, but renaming would likely fix it I assume because TS understands when you have 10 of the same named interface, they should be merged.

I do not wish to debate it further, but by insisting on being different than all other addons, you may be breaking things for other users and I do not understand why you would not want to be as compatible as possible. Again, it's not my addon, so if you insist on keeping it broken, feel free, but I do not want to debate it anymore. I am not using this addon, so it doesn't matter much to me.

**Pull request closed without merging**
